version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n_custom_video
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - "N8N_RESTRICT_FILE_ACCESS_TO=/data/files/"
      - NODES_EXCLUDE=[]
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./local_files:/data/files